# cargo-features = ["extra-link-arg"]

[package]
name = "loader-shim"
version = "0.1.0"
authors = ["PRoot Developers <proot_me@googlegroups.com>"]
edition = "2021"

[dependencies]
sc = { git = "https://github.com/japaric/syscall.rs.git", rev = "053dc07c4e9f1399c548ee294253015c7c9682bd" }
compiler_builtins = { version = "0.1.160", optional = true, features = [ "mem" ] }

[features]
build-binary = [ "compiler_builtins" ]

[[bin]]
name = "loader-shim"
required-features = ["build-binary"] # crate `rlibc` is required only when build executable files
