[package]
name = "proot-rs"
version = "0.1.0"
authors = ["PRoot Developers <proot_me@googlegroups.com>"]
edition = "2021"

[dependencies]
libc = "0.2.25"
nix = "0.24.1"
clap = { version = "4.5.54", features = ["cargo"] }
sc = { git = "https://github.com/japaric/syscall.rs.git", rev = "053dc07c4e9f1399c548ee294253015c7c9682bd" }
lazy_static = "1.4.0"
byteorder = "1.1.0"
log = "0.4.14"
env_logger = "0.11.8"
loader-shim = { path = "../loader-shim" }

[dev-dependencies]
nc = "0.7.5"
